version: "3"

services:
  node:
    build: .
    container_name: marketplace
    tty: true
    stdin_open: true
    command: sh
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3002:3002
    env_file: .env
    environment:
      MYSQLHOST: db

  db:
    image: mysql:8.0.32
    container_name: marketplace_db
    restart: unless-stopped
    env_file: .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD}

networks:
  default:
    name: marketplace_net